ServicioClientes/ServicioClientes/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace ServicioClientes.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {

        }
            public DbSet<Cliente> Cliente { get; set; }
    }
}

ServicioClientes/ServicioClientes/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ServicioClientes.Models
{
    public class Cliente
    {
        [Key]
        public int Cid { get; set; }

        [Required(ErrorMessage = "Ingresa el nombre del cliente")]
        [Display(Name = "Nombre del cliente")]
        public string Cname { get; set; }

        [Required(ErrorMessage = "Ingresa el apellido del cliente")]
        [Display(Name = "Apellido del cliente")]
        public string Capell { get; set; }

        [Required(ErrorMessage = "Ingresa el email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Ingresa un email valido")]
        public string Cmail { get; set; }

        [Required(ErrorMessage = "Enter the employee salary")]
        [Display(Name = "Saldo")]
        public int Csaldo { get; set; }
    }
}

ServicioClientes/ServicioClientes/Models/ErrorViewModel.cs
using System;

namespace ServicioClientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ServicioClientes/ServicioClientes/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServicioClientes.Models;

namespace ServicioClientes.Controllers
{
    public class ClienteController : Controller
    {

        private readonly ApplicationDbContext _db;

        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            var displaydata = _db.Cliente.ToList();
            return View(displaydata);
        }
        [HttpGet]

        public async Task<IActionResult> Index(String cSearch)

        {
            ViewData["GetEmployeesDetails"] = cSearch;
            var empquery = from x in _db.Cliente select x;
            if (!String.IsNullOrEmpty(cSearch))
            {
                empquery = empquery.Where(x => x.Cname.Contains(cSearch) || x.Cmail.Contains(cSearch));

            }
            return View(await empquery.AsNoTracking().ToListAsync());

        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Cliente nCLT)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nCLT);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(nCLT);

        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getCDetail = await _db.Cliente.FindAsync(id);
            return View(getCDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getCDetail = await _db.Cliente.FindAsync(id);
            return View(getCDetail);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(Cliente vCLT)

        {
            if (ModelState.IsValid)
            {
                _db.Update(vCLT);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(vCLT);

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getCDetails = await _db.Cliente.FindAsync(id);
            return View(getCDetails);
        }

        [HttpPost]

        public async Task<IActionResult> Delete(int id)

        {
            var getCDetail = await _db.Cliente.FindAsync(id);
            _db.Cliente.Remove(getCDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");

        }

    }
}

ServicioClientes/ServicioClientes/Views/Cliente/Create.cshtml
@model ServicioClientes.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
            <div class="form-group">
                <label asp-for="Cname" class="control-label"></label>
                <input asp-for="Cname" class="form-control" />
                <span asp-validation-for="Cname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capell" class="control-label"></label>
                <input asp-for="Capell" class="form-control" />
                <span asp-validation-for="Capell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmail" class="control-label"></label>
                <input asp-for="Cmail" class="form-control" />
                <span asp-validation-for="Cmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Csaldo" class="control-label"></label>
                <input asp-for="Csaldo" class="form-control" />
                <span asp-validation-for="Csaldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ServicioClientes/ServicioClientes/Views/Cliente/Delete.cshtml
@model ServicioClientes.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Quieres eliminar este cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capell)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capell)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Csaldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Csaldo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ServicioClientes/ServicioClientes/Views/Cliente/Detail.cshtml
@model ServicioClientes.Models.Cliente

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles del cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capell)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capell)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Csaldo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Csaldo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ServicioClientes/ServicioClientes/Views/Cliente/Edit.cshtml
@model ServicioClientes.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cid" class="control-label"></label>
                <input asp-for="Cid" class="form-control" />
                <span asp-validation-for="Cid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cname" class="control-label"></label>
                <input asp-for="Cname" class="form-control" />
                <span asp-validation-for="Cname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capell" class="control-label"></label>
                <input asp-for="Capell" class="form-control" />
                <span asp-validation-for="Capell" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cmail" class="control-label"></label>
                <input asp-for="Cmail" class="form-control" />
                <span asp-validation-for="Cmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Csaldo" class="control-label"></label>
                <input asp-for="Csaldo" class="form-control" />
                <span asp-validation-for="Csaldo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ServicioClientes/ServicioClientes/Views/Cliente/Index.cshtml
@model IEnumerable<ServicioClientes.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get">

    <p>
        <input type="search" placeholder="Ingresa Nombre o Email para realizar busqueda:" name="cSearch"
               value="@ViewData["GetCDetails"]" style="width= 500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver Todos los clientes</a>
    </p>

</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capell)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Csaldo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capell)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Csaldo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Cid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Detail", new { id = item.Cid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Cid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

ServicioClientes/ServicioClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ServicioClientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index">ServicioClientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Home</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ServicioClientes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>