Core_empleados/Core_empleados/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core_empleados.Models;

namespace Core_empleados.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Employee> Employee { get; set; }
    }
}

Core_empleados/Core_empleados/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_empleados.Models
{
    public class Employee
    {
        [Key]
        public int Empid { get; set; }

        [Required(ErrorMessage = "Enter the employee name")]
        [Display(Name = "Employee Name")]
        public string Empname { get; set; }

        [Required(ErrorMessage = "Enter the employee email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Enter a valid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter the employee age")]
        [Display(Name = "Age")]
        [Range(18, 50)]
        public int Age { get; set; }

        [Required(ErrorMessage = "Enter the employee salary")]
        [Display(Name = "Salary")]
        public int Salary { get; set; }
    }
}

Core_empleados/Core_empleados/Models/ErrorViewModel.cs
using System;

namespace Core_empleados.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_empleados/Core_empleados/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core_empleados.Models;
using Microsoft.AspNetCore.Mvc;

namespace Core_empleados.Controllers
{
    public class EmployeeController : Controller
    {

        private readonly ApplicationDbContext _db;

        public EmployeeController (ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            var displaydata = _db.Employee.ToList();
            return View(displaydata);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Employee nEMP)
        {
            if (ModelState.IsValid)
            {
                _db.Add(nEMP);
                      await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(nEMP);

        }

        public async Task<IActionResult> Detail(int? id)
        {
            if (id==null)
            {
                return RedirectToAction("Index");

            }
            var getEmpDetail= await _db.Employee.FindAsync(id);
            return View(getEmpDetail);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }
            var getEmpDetail = await _db.Employee.FindAsync(id);
            return View(getEmpDetail);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(Employee oldEmp)

        {
            if (ModelState.IsValid)
            {
                _db.Update(oldEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return View(oldEmp);

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDetails = await _db.Employee.FindAsync(id);
            return View(getEmpDetails);
        }

        [HttpPost]

        public async Task<IActionResult> Delete(int id)

        {
            var getEmpDetail = await _db.Employee.FindAsync(id);
            _db.Employee.Remove(getEmpDetail);
                await _db.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

Core_empleados/Core_empleados/Views/Employee/Create.cshtml
@model Core_empleados.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Crear Usuario</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Empname" class="control-label"></label>
                <input asp-for="Empname" class="form-control" />
                <span asp-validation-for="Empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_empleados/Core_empleados/Views/Employee/Delete.cshtml
@model Core_empleados.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar Usuario</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Core_empleados/Core_empleados/Views/Employee/Detail.cshtml
@model Core_empleados.Models.Employee

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles del usuario</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Empid }) |
    <a asp-action="Index">Back to List</a>
</div>

Core_empleados/Core_empleados/Views/Employee/Edit.cshtml
@model Core_empleados.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empid" class="control-label"></label>
                <input asp-for="Empid" class="form-control" readonly />
                <span asp-validation-for="Empid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Empname" class="control-label"></label>
                <input asp-for="Empname" class="form-control" />
                <span asp-validation-for="Empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_empleados/Core_empleados/Views/Employee/Index.cshtml
@model IEnumerable<Core_empleados.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Usuarios</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Empid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Empid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Empid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Detail", new { id = item.Empid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Empid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Core_empleados/Core_empleados/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_empleados</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="Index">Core_empleados</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Core_empleados 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>